### PR TITLE
Add --fail-fast option to .rspec configuration

### LINKED ISSUE #1117: Development - add a fail-fast option to the travis builds
### Descriptive summary

The travis builds take a very long time.  Adding a fail-fast option might help to speed things up.

### PR DESCRIPTION
**Pull request by darrenleeweber**
Fixes #1117 

@samvera-labs/hyrax-code-reviewers

### CODE REVIEW

**Comment by jcoyne** [comment]
I'd prefer we don't do this. If we pay the cost for test set up (about 12 min) I want to see all the things that are failing

**Comment by atz** [comment]
I agree w/ Justin on this one.  Might as well see all the broken things at once.  Otherwise, you are having to fail many times serially just to get the same information.

**Comment by jeremyf** [comment]
I also agree with @jcoyne. I find the `.rspec` to be a place of surprises and not immediately obvious behavior. I would rather provide documentation that explains how to add the `--fail-fast` to the integration test.

From https://apidock.com/rspec/Spec/Rake/SpecTask

```
$ bundle exec rake SPEC_OPTS="--fail-fast"
```

**Comment by mjgiarlo** [comment]
Given the above feedback, this is not a change we're going to pursue at this time. Thanks for your efforts to speed up the build, @darrenleeweber!

**Pull request closed without merging**
