### PR TITLE
Use private access

### PR DESCRIPTION
**Pull request by jcoyne**
I think we had a misunderstanding about what private access means in
Ruby.  It's different rules than in Java

### CODE REVIEW

**Comment by jcoyne** [comment]
@mjgiarlo it does say:

```
I think we had a misunderstanding about what private access means in
Ruby.  It's different rules than in Java
```

**Comment by mjgiarlo** [comment]
@jcoyne I know, but that doesn't tell me what this gains us. Extra security? etc. Like I said, I won't block over this.

**Comment by jcoyne** [comment]
@mjgiarlo it gains us nothing. It was a mistake to use protected in the first place.

**Comment by jcoyne** [comment]
Say we have an class Foo: 

```ruby
class Foo
   def call_bar(obj)
     obj.bar
   end

   protected
   def bar
   end
end

foo1 = Foo.new
foo2 = Foo.new

foo1.call_bar(foo2)
#=> nil

class Baz
   def call_bar(obj)
     obj.bar
   end

   private
   def bar
   end
end


baz1 = Baz.new
baz2 = Baz.new

baz1.call_bar(baz2)
NoMethodError: private method `bar' called for #<Baz:0x007ffcef8afe78>
```

**Comment by mjgiarlo** [comment]
@jcoyne OK. Thanks for clarifying.

**Pull request merged**
