### PR TITLE
Params permitted in ContentBlocks controller should match those sent by form

### LINKED ISSUE #1072: Content blocks not saving content
### Descriptive summary
Adding content to content blocks and saving does not actually save them. 

### Expected behavior
On save, the content of a content block should be saved.

### Actual behavior
On save, the content of the content block is not saved. 

### Steps to reproduce the behavior

1. enter text into a content block
2. save the block
3. go to the view for the content block and note that it is not saved

I have confirmed that this works on the Hyku test environment. One major difference i see between the two systems is that when one selects Content Block from the Dashboard, one is not immediately entered into one of the content blocks for editing. In Hyku, one is dropped right into the About Page content block.

### PR DESCRIPTION
**Pull request by mjgiarlo**
This was a goof of mine -- I changed the controller without adjusting its tests, so we missed this.

Fixes #1072

### CODE REVIEW

**Comment by atz** [comment]
What explains this difference in Travis?
```
 3282.1 Ruby: 2.4.1 RAILS_VERSION=5.0.3 18 min 45 sec
 3282.2 Ruby: 2.4.1 RAILS_VERSION=5.1.1 49 min 58 sec
```

**Comment by mjgiarlo** [comment]
Is it the Rails 5.1 builds with the timeout issues, consistently? If so, I don't care that much about being on the bleeding edge.

**Comment by jcoyne** [comment]
I think it has far more to do with how busy the vm that our travis build is running on than anything we have control over.

**Comment by jcoyne** [comment]
I re-ran the 5.1 build and it completed in under 24 minutes.

**Pull request merged**
