### PR TITLE
Remove unused ClassifyConcern class

### PR DESCRIPTION
**Pull request by jcoyne**
This class mostly consisted of unused code that was originally from Curate.

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@tpendragon @jeremyf ?

**Comment by tpendragon** [comment]
We use `Hyrax::ClassifyConcern.new.all_curation_concern_classes`, but we can always change it to what's in this PR. Breaking change, though.

**Comment by jcoyne** [comment]
@tpendragon can you show me where you're using it?

**Comment by mjgiarlo** [comment]
https://github.com/pulibrary/plum/blob/ce34a948414084fc49c8e34cf66ef28d9bcd20f9/app/controllers/welcome_controller.rb

**Comment by tpendragon** [comment]
@jcoyne It's trivial, I'm not blocking this PR over it: https://github.com/pulibrary/plum/blob/master/app/controllers/welcome_controller.rb#L3. It's just the definition of breaking - seems safe to ship with 2.0 though.

**Comment by jcoyne** [comment]
@tpendragon Sounds good. I think `Hyrax.config.curation_concerns` would be a reasonable replacement, right?

**Comment by tpendragon** [comment]
@jcoyne Yes, like I said I can change it to that.

**Comment by jeremyf** [comment]
Yes. This is something to remove. At one point we, at Notre Dame, needed to handle what work types existed and what were "on the horizon". This class can go away!

**Comment by atz** [comment]
Consensus achieved.

**Pull request merged**
